version: '3.9'
services:
  activemq:
    image: webcenter/activemq
    restart: always
    ports:
      - '61616:61616'
      - '8161:8161'
    networks:
      - bsc-gms-network

networks:
  bsc-gms-network:
    driver: bridge
